# .github/recent-activity.config.yml
activity:
  include:
    - pushes
    - pull_requests
    - comments
  repositories:
    - Ethousand/Git-github-2024
    - Ethousand/Ethousand

commit_count: 5
show_prs: true
show_comments: true