# This is a basic workflow to help you get started with Actions

name: Update README with Recent Commits

on:
  schedule:
    - cron: '* */24 * * *'  # Ejecuta cada 24 horas
  workflow_dispatch:        # Permite ejecución manual

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Permite escribir en el repositorio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Readme-Wrokflows/recent-activity@v2.4.1
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
