name: Update README with Recent Commits

on:
  schedule:
    - cron: '0 */12 * * *'  # Ejecuta cada 12 horas
  workflow_dispatch:        # Permite ejecución manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Permite escribir en el repositorio

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: Readme-Workflows/recent-activity@2.4.1
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

